# Generated by Django 5.0.4 on 2024-04-24 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(max_length=100)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z]{2}[0-9]{3}[A-Z]{3})$')])),
                ('car_colour', models.CharField(max_length=50)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carmake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
