# Generated by Django 5.0.4 on 2024-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carmake_id_remove_carmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
